name: MatiPlugin
version: 1.0
main: me.jokur.nauka.MatiPlugin
commands:
  gracze:
    description: "Pokazuje liczbę graczy"
    usage: /gracze
  dzien:
    description: "Nastaje dzień"
    usage: /dzien
  noc:
    description: "Nastaje noc"
    usage: /noc
  gm:
    description: "Wybierz jeden z trybów gamemode(1 - Survival, 2 - Creative, 3 - Adventure, 4 - Spectator), tyle, że szybciej"
    usage: /gm
  sethome:
    description: "Ustawiasz home"
    usage: /sethome
  home:
    description: "Tepasz się do home"
    usage: /home
  pogoda:
    description: "Ustawiasz pogodę na bezchmurną"
    usage: /pogoda
  sklep:
    description: "Tepa cię do sklepu"
    usage: /sklep
  spawn:
    description: "Tepa cię na spawn"
    usage: /spawn
  setsecurity:
    description: "Ustawiasz obszar strzeżony"
    usage: /setsecurity
